In [1]:
import xarray as xr
import datetime as dt
import numpy as np

In [2]:
# set runing dates:
startday = [dt.datetime(2016,12,25)+dt.timedelta(days=i) for i in range(int(406))]
# print(len(startday))
folders = [dt.datetime(2016,12,25)+dt.timedelta(days=7*(i+1)) for i in range(int(58))]
folders = np.repeat(folders,7)

In [3]:
startday[66]

datetime.datetime(2017, 3, 1, 0, 0)

In [4]:
drop_vars = (
        "sbu", "tauuo", "time_counter_bounds", "time_instant_bounds", "uos", "time_instant",
    )

files = ["/ocean/mdunphy/CIOPSW-BC12/{:%Y%m%d}00/BC12_1h_grid_U_2D_{:%Y%m%d}_{:%Y%m%d}.nc".format(folders[i], startday[i],startday[i]) for i in [66,67]]

mydata = xr.open_mfdataset(files, drop_variables=drop_vars)
ogu_h = mydata['ubar']

In [5]:
ogu_h

<xarray.DataArray 'ubar' (time_counter: 48, y: 1020, x: 714)>
dask.array<concatenate, shape=(48, 1020, 714), dtype=float32, chunksize=(24, 1020, 714), chunktype=numpy.ndarray>
Coordinates:
    nav_lat       (y, x) float32 dask.array<chunksize=(1020, 714), meta=np.ndarray>
    nav_lon       (y, x) float32 dask.array<chunksize=(1020, 714), meta=np.ndarray>
  * time_counter  (time_counter) datetime64[ns] 2017-03-01T01:00:00 ... 2017-...
Dimensions without coordinates: y, x
Attributes:
    long_name:           ocean barotropic current along i-axis
    units:               m/s
    online_operation:    instant
    interval_operation:  60 s
    interval_write:      1 h
    cell_methods:        time: point (interval: 60 s)

In [6]:
drop_vars = (
        "sbu", "tauuo", "time_counter_bounds", "time_instant_bounds", "uos", "time_instant", "depthu_bounds",
    )

files = ["/ocean/mdunphy/CIOPSW-BC12/{:%Y%m%d}00/BC12_1d_grid_U_{:%Y%m%d}_{:%Y%m%d}.nc".format(folders[i], startday[i],startday[i]) for i in [65,66]]

mydata = xr.open_mfdataset(files, drop_variables=drop_vars)
ogu_d = mydata['uo']

In [7]:
mydata = xr.open_dataset("/ocean/rbeutel/data/{:%Y%m}/U_new_{:%Y%m%d}.nc".format(startday[66],startday[66]), drop_variables=drop_vars)
new = mydata['vozocrtx']

In [47]:
ogu_d

<xarray.DataArray 'uo' (time_counter: 2, depthu: 75, y: 1020, x: 714)>
dask.array<concatenate, shape=(2, 75, 1020, 714), dtype=float32, chunksize=(1, 75, 1020, 714), chunktype=numpy.ndarray>
Coordinates:
  * depthu        (depthu) float32 0.5075 1.558 2.669 ... 5.698e+03 5.902e+03
    nav_lat       (y, x) float32 dask.array<chunksize=(1020, 714), meta=np.ndarray>
    nav_lon       (y, x) float32 dask.array<chunksize=(1020, 714), meta=np.ndarray>
  * time_counter  (time_counter) datetime64[ns] 2017-03-01 2017-03-02
Dimensions without coordinates: y, x
Attributes:
    standard_name:       sea_water_x_velocity
    long_name:           Sea Water X Velocity
    units:               m/s
    online_operation:    instant
    interval_operation:  1 d
    interval_write:      1 d
    cell_methods:        time: point

In [33]:
# the day average over all depths in this location is always +ve 
ogu_d[0,:,646,265].values

array([0.05385605, 0.05247176, 0.05210696, 0.05163509, 0.05115515,
       0.05086089, 0.05056046, 0.05019301, 0.04967367, 0.04916609,
       0.04841049, 0.04742363, 0.04640344, 0.04483606, 0.04166612,
       0.03764721, 0.03110924, 0.02754123, 0.02360993, 0.02757634,
       0.03318494, 0.03907347, 0.04152552, 0.03514143, 0.02778851,
       0.03211543, 0.03244721, 0.03670004, 0.07619993, 0.08704666,
       0.05015881, 0.06499825, 0.08283985, 0.06601611, 0.0431298 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [36]:
ogu_h.time_counter[0]

<xarray.DataArray 'time_counter' ()>
array('2017-03-01T01:00:00.000000000', dtype='datetime64[ns]')
Coordinates:
    time_counter  datetime64[ns] 2017-03-01T01:00:00
Attributes:
    axis:           T
    standard_name:  time
    long_name:      Time axis
    time_origin:    1950-01-01 00:00:00
    bounds:         time_counter_bounds

In [49]:
# it is the baroclinic velocity that fluctuates between positive and negative to give the effect of tides
ogu_h[:,646,265].values

array([-0.05737844, -0.07661172, -0.06857672, -0.0386265 ,  0.01136163,
        0.06766678,  0.11910083,  0.17878528,  0.203213  ,  0.16570258,
        0.09281689,  0.01169961, -0.05049176, -0.07922053, -0.08015012,
       -0.05650135, -0.01253048,  0.03810858,  0.08215523,  0.13516977,
        0.18495223,  0.17659418,  0.1121624 ,  0.03930151, -0.02351309,
       -0.05968415, -0.06698097, -0.0552518 , -0.02048282,  0.02663545,
        0.0721687 ,  0.12965754,  0.18391053,  0.1828286 ,  0.12730263,
        0.05269662, -0.02272792, -0.07578255, -0.09626286, -0.09259185,
       -0.06865719, -0.02665541,  0.02430845,  0.07267823,  0.13765769,
        0.18162881,  0.1565711 ,  0.08635972], dtype=float32)

In [10]:
#time when the baroclinic was negative, the new is mostly negative
new[0,646,265,:]

<xarray.DataArray 'vozocrtx' (depthu: 75)>
array([-0.00664 , -0.007999, -0.008369, -0.008843, -0.009324, -0.009627,
       -0.009936, -0.010309, -0.010829, -0.01134 , -0.012091, -0.013068,
       -0.014083, -0.015671, -0.018843, -0.022939, -0.029578, -0.033273,
       -0.037236, -0.033041, -0.027486, -0.021746, -0.019132, -0.025607,
       -0.032643, -0.028438, -0.02794 , -0.023684,  0.016076,  0.026616,
       -0.009853,  0.005642,  0.023051,  0.0059  , -0.016831,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan])
Coordinates:
    time_counter  datetime64[ns] 2017-03-01T01:00:00
    nav_lat       float32 ...
    nav_lon       float32 ...
  * depthu        (depthu) float32 0.5075 1.558 2.669 ... 5.698e+03 5.902e+03

In [50]:
#and a time when it was positive the new is all positive
new[6,646,265,:]

<xarray.DataArray 'vozocrtx' (depthu: 75)>
array([0.166952, 0.165742, 0.165337, 0.164857, 0.16437 , 0.164014, 0.163653,
       0.163242, 0.162718, 0.162187, 0.161466, 0.160548, 0.159562, 0.157851,
       0.154668, 0.150109, 0.142867, 0.13841 , 0.134254, 0.139818, 0.145053,
       0.149904, 0.153492, 0.146464, 0.141335, 0.144806, 0.146301, 0.150577,
       0.191896, 0.200599, 0.166644, 0.186072, 0.200885, 0.181767, 0.159966,
            nan,      nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan])
Coordinates:
    time_counter  datetime64[ns] 2017-03-01T07:00:00
    nav_lat       float32 ...
    nav_lon       float32 ...
  * depthu        (depthu) float32 0.5075 1.558 2.669 ... 5.698e+03 5.902e+03

# Go through the process again to see if you get the same results!

In [12]:
mydata = xr.open_dataset("/ocean/mdunphy/CIOPSW-BC12/grid/mesh_mask_Bathymetry_NEP36_714x1020_SRTM30v11_NOAA3sec_WCTSS_JdeFSalSea.nc")
e3t = mydata['e3t_0']
e3t

<xarray.DataArray 'e3t_0' (t: 1, z: 75, y: 1020, x: 714)>
[54621000 values with dtype=float64]
Dimensions without coordinates: t, z, y, x

In [13]:
# convert e3t to e3u and to e3v
e3t_xshift = e3t.shift(x=-1,fill_value=0)
e3u = e3t_xshift+e3t
e3u = e3u*0.5
e3u = e3u.rename({'z': 'depthu'})
e3u = e3u.squeeze()

e3t_yshift = e3t.shift(y=-1,fill_value=0)
e3v = e3t_yshift+e3t
e3v = e3v*0.5
e3v = e3v.rename({'z': 'depthv'})

In [14]:
# hourly is already in barotropic form so no need to do conversion
ogu_h

<xarray.DataArray 'ubar' (time_counter: 48, y: 1020, x: 714)>
dask.array<concatenate, shape=(48, 1020, 714), dtype=float32, chunksize=(24, 1020, 714), chunktype=numpy.ndarray>
Coordinates:
    nav_lat       (y, x) float32 dask.array<chunksize=(1020, 714), meta=np.ndarray>
    nav_lon       (y, x) float32 dask.array<chunksize=(1020, 714), meta=np.ndarray>
  * time_counter  (time_counter) datetime64[ns] 2017-03-01T01:00:00 ... 2017-...
Dimensions without coordinates: y, x
Attributes:
    long_name:           ocean barotropic current along i-axis
    units:               m/s
    online_operation:    instant
    interval_operation:  60 s
    interval_write:      1 h
    cell_methods:        time: point (interval: 60 s)

In [15]:
# need to calculate baroclinic component of daily 
ut_d = (ogu_d*e3u).sum(dim='depthu')/e3u.sum(dim='depthu')

In [37]:
ut_d[0,646,265].values

array(0.0026359)

In [17]:
#subtract from u to get baroclinic component
uc_d = ogu_d-ut_d

In [38]:
uc_d[0,:,646,265].values #all water values still positive

array([ 0.05122015,  0.04983586,  0.04947106,  0.04899919,  0.04851925,
        0.04822499,  0.04792455,  0.04755711,  0.04703777,  0.04653019,
        0.04577459,  0.04478773,  0.04376754,  0.04220016,  0.03903022,
        0.0350113 ,  0.02847333,  0.02490533,  0.02097402,  0.02494044,
        0.03054904,  0.03643757,  0.03888962,  0.03250553,  0.02515261,
        0.02947953,  0.02981131,  0.03406414,  0.07356403,  0.08441076,
        0.0475229 ,  0.06236234,  0.08020395,  0.06338021,  0.0404939 ,
       -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 ,
       -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 ,
       -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 ,
       -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 ,
       -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 ,
       -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 ,
       -0.0026359 , -0.0026359 , -0.0026359 , -0.0026359 , -0.00

In [19]:
offset = dt.timedelta(hours=1)
uc_h_interp = uc_d.resample(time_counter="1H", loffset=offset).interpolate("linear")

In [55]:
uc_h_interp[9,:,646,265].values #still positive

array([ 0.04640802,  0.04527206,  0.04485047,  0.04436592,  0.04387593,
        0.04349425,  0.0431074 ,  0.04267781,  0.04215114,  0.04161033,
        0.04090469,  0.04001619,  0.0390444 ,  0.03727116,  0.0340825 ,
        0.02929232,  0.02174837,  0.01691119,  0.01265871,  0.01890717,
        0.02398213,  0.0283881 ,  0.03246264,  0.02515982,  0.02098401,
        0.02408724,  0.0260817 ,  0.03036665,  0.07246526,  0.08024991,
        0.04755127,  0.06894603,  0.08246089,  0.06236047,  0.04102451,
       -0.00249851, -0.00249851, -0.00249851, -0.00249851, -0.00249851,
       -0.00249851, -0.00249851, -0.00249851, -0.00249851, -0.00249851,
       -0.00249851, -0.00249851, -0.00249851, -0.00249851, -0.00249851,
       -0.00249851, -0.00249851, -0.00249851, -0.00249851, -0.00249851,
       -0.00249851, -0.00249851, -0.00249851, -0.00249851, -0.00249851,
       -0.00249851, -0.00249851, -0.00249851, -0.00249851, -0.00249851,
       -0.00249851, -0.00249851, -0.00249851, -0.00249851, -0.00

In [27]:
u_new = ogu_h  + uc_h_interp

In [42]:
uc_h_interp.time_counter[0]

<xarray.DataArray 'time_counter' ()>
array('2017-03-01T01:00:00.000000000', dtype='datetime64[ns]')
Coordinates:
    time_counter  datetime64[ns] 2017-03-01T01:00:00

In [41]:
ogu_h.time_counter[0]

<xarray.DataArray 'time_counter' ()>
array('2017-03-01T01:00:00.000000000', dtype='datetime64[ns]')
Coordinates:
    time_counter  datetime64[ns] 2017-03-01T01:00:00
Attributes:
    axis:           T
    standard_name:  time
    long_name:      Time axis
    time_origin:    1950-01-01 00:00:00
    bounds:         time_counter_bounds

In [39]:
u_new.time_counter[0]

<xarray.DataArray 'time_counter' ()>
array('2017-03-01T01:00:00.000000000', dtype='datetime64[ns]')
Coordinates:
    time_counter  datetime64[ns] 2017-03-01T01:00:00
Attributes:
    axis:           T
    standard_name:  time
    long_name:      Time axis
    time_origin:    1950-01-01 00:00:00
    bounds:         time_counter_bounds

In [30]:
u_new[0,646,265,:].values

array([-0.00663951, -0.00799896, -0.00836945, -0.00884258, -0.00932353,
       -0.00962653, -0.00993561, -0.01030926, -0.01082934, -0.01134024,
       -0.01209085, -0.01306787, -0.01408322, -0.01567118, -0.01884299,
       -0.02293904, -0.02957761, -0.03327253, -0.03723595, -0.03304133,
       -0.0274861 , -0.02174583, -0.01913152, -0.02560749, -0.03264269,
       -0.02843814, -0.0279401 , -0.02368406,  0.01607571,  0.02661623,
       -0.0098527 ,  0.00564227,  0.0230512 ,  0.00589979, -0.01683149,
       -0.06000061, -0.06000061, -0.06000061, -0.06000061, -0.06000061,
       -0.06000061, -0.06000061, -0.06000061, -0.06000061, -0.06000061,
       -0.06000061, -0.06000061, -0.06000061, -0.06000061, -0.06000061,
       -0.06000061, -0.06000061, -0.06000061, -0.06000061, -0.06000061,
       -0.06000061, -0.06000061, -0.06000061, -0.06000061, -0.06000061,
       -0.06000061, -0.06000061, -0.06000061, -0.06000061, -0.06000061,
       -0.06000061, -0.06000061, -0.06000061, -0.06000061, -0.06

In [51]:
ogu_h[0,646,265].values

array(-0.05737844)

In [54]:
uc_h_interp[0,:,646,265].values

array([ 0.05073894,  0.04937948,  0.049009  ,  0.04853586,  0.04805492,
        0.04775192,  0.04744284,  0.04706918,  0.04654911,  0.04603821,
        0.0452876 ,  0.04431057,  0.04329523,  0.04170726,  0.03853545,
        0.03443941,  0.02780084,  0.02410592,  0.02014249,  0.02433711,
        0.02989235,  0.03563262,  0.03824692,  0.03177095,  0.02473575,
        0.0289403 ,  0.02943835,  0.03369439,  0.07345416,  0.08399467,
        0.04752574,  0.06302071,  0.08042965,  0.06327823,  0.04054696,
       -0.00262216, -0.00262216, -0.00262216, -0.00262216, -0.00262216,
       -0.00262216, -0.00262216, -0.00262216, -0.00262216, -0.00262216,
       -0.00262216, -0.00262216, -0.00262216, -0.00262216, -0.00262216,
       -0.00262216, -0.00262216, -0.00262216, -0.00262216, -0.00262216,
       -0.00262216, -0.00262216, -0.00262216, -0.00262216, -0.00262216,
       -0.00262216, -0.00262216, -0.00262216, -0.00262216, -0.00262216,
       -0.00262216, -0.00262216, -0.00262216, -0.00262216, -0.00

### cant see anything weird in U - try V

In [59]:
drop_vars = (
        "sbv", "tauvo", "time_counter_bounds", "time_instant_bounds", "vos", "time_instant",
    )

files = ["/ocean/mdunphy/CIOPSW-BC12/{:%Y%m%d}00/BC12_1h_grid_V_2D_{:%Y%m%d}_{:%Y%m%d}.nc".format(folders[i], startday[i],startday[i]) for i in [66,67]]

mydata = xr.open_mfdataset(files, drop_variables=drop_vars)
v_h = mydata['vbar']

In [72]:
v_h[0,646,245].values

array(-0.01526981)

In [61]:
drop_vars = (
        "sbv", "tauvo", "time_counter_bounds", "time_instant_bounds", "vos", "time_instant", "depthv_bounds",
    )

files = ["/ocean/mdunphy/CIOPSW-BC12/{:%Y%m%d}00/BC12_1d_grid_V_{:%Y%m%d}_{:%Y%m%d}.nc".format(folders[i], startday[i],startday[i]) for i in [65,66]]

mydata = xr.open_mfdataset(files, drop_variables=drop_vars)
v_d = mydata['vo']

In [69]:
v_d[0,:,646,245].values

array([0.06788421, 0.06744044, 0.06725351, 0.06709404, 0.06700248,
       0.06698276, 0.06708896, 0.06743433, 0.06804571, 0.06891254,
       0.07012153, 0.07152751, 0.07284092, 0.07363124, 0.07436211,
       0.07690813, 0.08209664, 0.09636344, 0.0974438 , 0.09506078,
       0.10035462, 0.11028419, 0.12608168, 0.14118093, 0.14787558,
       0.15333503, 0.14704806, 0.13404341, 0.11153904, 0.10320674,
       0.09899796, 0.08860412, 0.10963497, 0.09278838, 0.11631912,
       0.09895536, 0.10534582, 0.09403563, 0.07374241, 0.04003533,
       0.0209775 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [64]:
mydata = xr.open_dataset("/ocean/rbeutel/data/{:%Y%m}/V_new_{:%Y%m%d}.nc".format(startday[66],startday[66]), drop_variables=drop_vars)
new = mydata['vomecrty']

In [66]:
new[0, 646, 265,:]

<xarray.DataArray 'vomecrty' (depthv: 75)>
array([-0.131544, -0.131431, -0.131598, -0.131819, -0.131946, -0.131984,
       -0.131923, -0.131827, -0.131726, -0.131562, -0.131483, -0.131293,
       -0.131056, -0.130585, -0.129381, -0.12765 , -0.123484, -0.117905,
       -0.108261, -0.098466, -0.08729 , -0.081731, -0.075712, -0.073276,
       -0.071538, -0.058635, -0.045487, -0.033065, -0.016157,  0.017924,
        0.050966,  0.048351,  0.004595, -0.043794, -0.037982, -0.084627,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan])
Coordinates:
    time_counter  datetime64[ns] 2017-03-01T01:00:00
    nav_lat       float32 ...
    nav_lon       float32 ...
  * depthv        (depthv) float32 0.5075 1.558 2.669 ... 5.698e+03 5.902e+03

In [74]:
# need to calculate baroclinic component of daily 
vt_d = (v_d*e3v).sum(dim='depthv')/e3v.sum(dim='depthv')

In [75]:
vc_d = v_d-vt_d

In [76]:
offset = dt.timedelta(hours=1)
vc_h_interp = vc_d.resample(time_counter="1H", loffset=offset).interpolate("linear")

In [77]:
v_new = v_h  + vc_h_interp

In [79]:
v_new[0,646,265,:].values

array([[-0.131544  ],
       [-0.13143116],
       [-0.13159831],
       [-0.13181857],
       [-0.13194602],
       [-0.13198377],
       [-0.13192283],
       [-0.13182736],
       [-0.13172624],
       [-0.1315625 ],
       [-0.13148304],
       [-0.13129297],
       [-0.13105626],
       [-0.13058503],
       [-0.12938086],
       [-0.12765022],
       [-0.12348411],
       [-0.11790491],
       [-0.10826108],
       [-0.09846578],
       [-0.08728954],
       [-0.08173108],
       [-0.07571244],
       [-0.07327624],
       [-0.07153802],
       [-0.05863526],
       [-0.04548674],
       [-0.03306462],
       [-0.01615657],
       [ 0.01792394],
       [ 0.05096625],
       [ 0.04835082],
       [ 0.00459512],
       [-0.04379416],
       [-0.03798174],
       [-0.08462742],
       [-0.18360813],
       [-0.18360813],
       [-0.18360813],
       [-0.18360813],
       [-0.18360813],
       [-0.18360813],
       [-0.18360813],
       [-0.18360813],
       [-0.18360813],
       [-0